name: Secure Deployment
on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JS_DIR: assets/js  # 👈 Directory with your JS files

    steps:
      - uses: actions/checkout@v4

      - name: Verify File Structure
        run: |
          echo "Repository contents:"
          ls -la
          echo "\nChecking JS directory:"
          ls -la ${{ env.JS_DIR }}
          if [ ! -f "${{ env.JS_DIR }}/blogger-api.js" ]; then
            echo "❌ blogger-api.js missing in ${{ env.JS_DIR }}"
            exit 1
          fi

      - name: Replace Secrets
        working-directory: ${{ env.JS_DIR }}
        env:
          BLOGGER_KEY: ${{ secrets.BLOGGER_API_KEY }}
          KNOWLEDGE_SECRET: ${{ secrets.KNOWLEDGE_BASE }}
        run: |
          # Escape special characters using pipe delimiter
          sed -i "s|GITHUB_PLACEHOLDER1|$BLOGGER_KEY|g" blogger-api.js
          sed -i "s|GITHUB_PLACEHOLDER2|$KNOWLEDGE_SECRET|g" blogger-api.js
          sed -i "s|GITHUB_PLACEHOLDER3|$KNOWLEDGE_SECRET|g" other-file.js

      - name: Verify Replacements
        working-directory: ${{ env.JS_DIR }}
        run: |
          if grep -qE 'GITHUB_PLACEHOLDER[1-3]' *.js; then
            echo "❌ Placeholders still exist!"
            exit 1
          fi
          echo "✅ All placeholders replaced successfully"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true  # Preserve directory structure
