name: Secure Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Navigate to JS directory
        working-directory: ./assets/js
        env:
          BLOGGER_KEY: ${{ secrets.BLOGGER_API_KEY }}
          KNOWLEDGE_SECRET: ${{ secrets.KNOWLEDGE_BASE }}
        run: |
          # Verify file existence
          if [ ! -f blogger-api.js ]; then
            echo "blogger-api.js not found in $(pwd)"
            exit 1
          fi

          # Escape and replace
          ESCAPED_BLOGGER=$(printf '%s\n' "$BLOGGER_KEY" | sed -e 's/[\/&]/\\&/g')
          ESCAPED_KNOWLEDGE=$(printf '%s\n' "$KNOWLEDGE_SECRET" | sed -e 's/[\/&]/\\&/g')

          sed -i "s/GITHUB_PLACEHOLDER1/${ESCAPED_BLOGGER}/g" blogger-api.js
          sed -i "s/GITHUB_PLACEHOLDER2/${ESCAPED_KNOWLEDGE}/g" rag-index.js

      - name: Verify Replacement
        working-directory: ./assets/js
        run: |
          if grep -qr 'GITHUB_PLACEHOLDER' .; then
            echo "Error: Placeholders remaining!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
